### PR TITLE
Fixes the autoload warnings

### PR DESCRIPTION
**Pull request by mickprev**
This PR : 

-  fixes the below warnings during a "composer install" and therefore allows to respect the PSR-4;
-  excludes the "Tests" folder when creating the archive

```
Class FunctionalPHP\FantasyLand\Helpful\Tests\StringMonoid located in ./vendor/functional-php/fantasy-land/src/FantasyLand/Helpful/Tests/StringMonoidLawsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class FunctionalPHP\FantasyLand\Helpful\Tests\NotAStringMonoid located in ./vendor/functional-php/fantasy-land/src/FantasyLand/Helpful/Tests/StringMonoidLawsTest.php does not comply with psr-4 autoloading standard. Skipping.
Class FunctionalPHP\FantasyLand\Helpful\Tests\MonoidLawsTest located in ./vendor/functional-php/fantasy-land/src/FantasyLand/Helpful/Tests/StringMonoidLawsTest.php does not comply with psr-4 autoloading standard. Skipping.
```

### CODE REVIEW

**Comment by mickprev** [comment]
Ping @widmogrod @krtek4

**Review by widmogrod — APPROVED** [review]

**Comment by widmogrod** [comment]
@mickprev could you re-push changes to this pull-request? I see that travis had issues and didn't cach this Pull Request.

**Comment by mickprev** [comment]
@widmogrod I just re-pushed :)

**Comment by mickprev** [comment]
One of the builds failed but I don't feel that my code is the cause :s

@widmogrod An idea?

**Comment by widmogrod** [comment]
Looks like maybe you will need to run `composer fix`

This is error message that we got from travis:
```
> php-cs-fixer fix --verbose --diff --dry-run --allow-risky=yes
359
360 In ToolInfo.php line 50:
361                         
362  [ErrorException]       
363  Undefined index: name  
364                         
365
366 Exception trace:
367  {closure}() at /home/travis/build/functional-php/fantasy-land/vendor/friendsofphp/php-cs-fixer/src/ToolInfo.php:50
368  PhpCsFixer\ToolInfo->getComposerInstallationDetails() at /home/travis/build/functional-php/fantasy-land/vendor/friendsofphp/php-cs-fixer/src/Console/WarningsDetector.php:49
369  PhpCsFixer\Console\WarningsDetector->detectOldVendor() at /home/travis/build/functional-php/fantasy-land/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:75
370  PhpCsFixer\Console\Application->doRun() at /home/travis/build/functional-php/fantasy-land/vendor/symfony/console/Application.php:143
371  Symfony\Component\Console\Application->run() at /home/travis/build/functional-php/fantasy-land/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:58
372
373. Script php-cs-fixer fix --verbose --diff --dry-run --allow-risky=yes handling the check-code event returned with error code 1
```

**Comment by mickprev** [comment]
The problem was already on the main branch. You had a dependency in the composer.lock file which did not declare a name in its composer.json file. Certainly that must have been a relic because this package (gecko-packages/gecko-php-unit)  does not seem to be used.

I took the opportunity to delete the composer.lock file because it is not necessary for this library (cf. https://getcomposer.org/doc/02-libraries.md#lock-file). It suits you?

It would also be interesting to updatePHPUnit later because version 5 is starting to be a bit dated :)

**Comment by mickprev** [comment]
Hi @widmogrod,

Can we merge this PR? :)

**Comment by widmogrod** [comment]
@mickprev  thank you for contribution! I released version 1.0.1, soon it should be propagated and ready to download via composer

**Pull request merged**
